### PR TITLE
 Fix a crash when repository uses custom flake8 format

### PR DESCRIPTION
**Pull request by gediminasz**
Hi,

First of all, thank you for this useful `gem`! I tried using it today on a project at work but encountered a crash similar to this:

```
Traceback (most recent call last):
        21: from /home/gedas/.rbenv/versions/2.5.0/bin/pronto:23:in `<main>'
        20: from /home/gedas/.rbenv/versions/2.5.0/bin/pronto:23:in `load'
        19: from /home/gedas/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/pronto-0.9.5/bin/pronto:6:in `<top (required)>'
        18: from /home/gedas/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
        17: from /home/gedas/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
        16: from /home/gedas/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
        15: from /home/gedas/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
        14: from /home/gedas/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/pronto-0.9.5/lib/pronto/cli.rb:60:in `run'
        13: from /home/gedas/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/pronto-0.9.5/lib/pronto/cli.rb:60:in `chdir'
        12: from /home/gedas/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/pronto-0.9.5/lib/pronto/cli.rb:61:in `block in run'
        11: from /home/gedas/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/pronto-0.9.5/lib/pronto.rb:64:in `run'
        10: from /home/gedas/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/pronto-0.9.5/lib/pronto/runners.rb:13:in `run'
         9: from /home/gedas/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/pronto-0.9.5/lib/pronto/runners.rb:13:in `each'
         8: from /home/gedas/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/pronto-0.9.5/lib/pronto/runners.rb:20:in `block in run'
         7: from /home/gedas/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/pronto-flake8-0.1.0/lib/pronto/flake8.rb:56:in `run'
         6: from /home/gedas/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/pronto-flake8-0.1.0/lib/pronto/flake8.rb:63:in `run_flake8'
         5: from /home/gedas/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/pronto-flake8-0.1.0/lib/pronto/flake8.rb:63:in `chdir'
         4: from /home/gedas/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/pronto-flake8-0.1.0/lib/pronto/flake8.rb:67:in `block in run_flake8'
         3: from /home/gedas/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/pronto-flake8-0.1.0/lib/pronto/flake8.rb:81:in `parse_output'
         2: from /home/gedas/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/pronto-flake8-0.1.0/lib/pronto/flake8.rb:81:in `map'
         1: from /home/gedas/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/pronto-flake8-0.1.0/lib/pronto/flake8.rb:81:in `block in parse_output'
/home/gedas/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/pronto-flake8-0.1.0/lib/pronto/flake8.rb:86:in `parse_output_line': undefined method `strip' for nil:NilClass (NoMethodError)
```

The problem was that our project is using a custom flake8 configuration which includes `format = pylint` option which does not print out the column in the error message. For reference: https://github.com/PyCQA/flake8/blob/9631dac52aa6ed8a3de9d0983c3c7b0267ae7d6d/src/flake8/formatting/default.py#L56

In other words, `splits` in [`parse_output_line`](https://github.com/scoremedia/pronto-flake8/blob/7c55f837af95b850b24f2297f2c64287f03f7f13/lib/pronto/flake8.rb#L84-L94) ends up being an array of 3 elements instead of 4, thus `message` is `nil` and we get a `NoMethodError`.

Here I provide a solution of overriding any custom flake8 format with the default using `--format=default`

I have also added `require 'tmpdir'` to `spec/support/repository_helper.rb` because I was getting the following error:

```
Failures:

  1) Pronto::Flake8#run patches are nil returns an empty array
     Failure/Error: @tmp_git_dir = Dir.mktmpdir

     NoMethodError:
       undefined method `mktmpdir' for Dir:Class
       Did you mean?  mkdir
     # ./spec/support/repository_helper.rb:7:in `create_repository'
     # ./spec/pronto/flake8_spec.rb:71:in `block (3 levels) in <module:Pronto>'
```

### CODE REVIEW

**Comment by gediminasz** [comment]
I have also updated the Python version used by Travis, because it kept failing with the following error:

```
$ pyenv global 3.5.3
pyenv: version `3.5.3' not installed
```

I have checked the available versions in this build: https://travis-ci.org/scoremedia/pronto-flake8/builds/438773783 (`pyenv versions` step)

**Comment by gediminasz** [comment]
@RAbraham did you have a chance to look through this PR?

**Comment by RAbraham** [comment]
@gediminasz Thanks for using the gem! I wasn't notified of this until yesterday. I'm a bit busy this week and next week, I'm leaving the company so I myself have to negotiate how I'll access this repo. I'll keep you posted.

**Comment by RAbraham** [comment]
@gediminasz Thank you for your contribution, especially the unit test.

**Comment by RAbraham** [comment]
@gediminasz I've pushed a `0.2.0` version out. Let me know how it goes.

**Comment by gediminasz** [comment]
@RAbraham Much appreciated! I've upgraded just now and it seems to work fine.

**Pull request merged**
